#!/bin/bash
pip install tables
pip install unidecode
pip install pandas
pip install scikit-learn
pip install voila
pip install ipywidgets
jupyter serverextension enable voila --sys-prefix
jupyter nbextension enable --py widgetsnbextension --sys-prefix
